# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:

  analyze:

    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout

      # Analyze
      - run:
          name: Detekt analysis
          command: ./gradlew -p dsl detekt && ./gradlew -p publish detekt

  test:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout
    
      - run:
          name: DSL test
          command: ./gradlew -p dsl :dsl:test
    
      - run:
          name: DSL Android test
          command: ./gradlew -p dsl :dsl-android:test

      - run:
          name: EasyPublish test
          command: ./gradlew -p publish test

  publish:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - run:
          name: "Publish DSL to Bintray"
          command: ./gradlew -p dsl uploadArchives

workflows:
  analyze_test_publish:
    jobs:
      - analyze
      - test
      - publish:
#          requires:
#            - analyze
#            - test
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^[0-9](\.[0-9]+)+(\-\w+\-[0-9]+){0,1}$/
