# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:

  analyze:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - run:
          name: Detekt analysis
          command: ./gradlew -p dsl detekt && ./gradlew -p publish detekt

  test_dsl:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout
    
      - run:
          name: DSL test
          command: ./gradlew -p dsl :dsl:test
    
      - run:
          name: DSL Android test
          command: ./gradlew -p dsl :dsl-android:test

  test_easy-publish:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - run:
          name: DSL test
          command: ./gradlew -p publish :plugin:test

  publish_dsl:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - run:
          name: "Publish DSL+ to Bintray and Gradle Central"
          command: ./gradlew -p dsl setupGradleKeys && ./gradlew -p dsl uploadArchives && ./gradlew -p dsl publishPlugins

  publish_easy-publish:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - run:
          name: "Publish EasyPublish to Gradle Central"
          command: ./gradlew -p dsl setupGradleKeys && ./gradlew -p publish publishPlugins

workflows:
  analyze_test_publish:
    jobs:
      - analyze:
          filters:
            tags:
              only: /.*/

      - test_dsl:
          filters:
            tags:
              only: /.*/

      - test_easy-publish:
          filters:
            tags:
              only: /.*/

      - publish_dsl:
          context:
            - Bintray
          requires:
            - analyze
            - test_dsl
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^dsl-[0-9](\.[0-9]+){1,2}(\-\w+\-[0-9]{1,2}){0,1}$/

      - publish_easy-publish:
          context:
            - Bintray
            - Maven
          requires:
            - analyze
            - test_easy-publish
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^publish-[0-9](\.[0-9]+){1,2}$/
