# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:

  analyze:

    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout

      # Analyze
      - run:
          name: Detekt analysis
          command: ./gradlew detekt

  test:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout
    
      - run:
          name: DSL test
          command: ./gradlew :dsl:test
    
      - run:
          name: DSL Android test
          command: ./gradlew :dsl-android:test

  publish_dsl:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - run:
          name: "Publish DSL+ to Bintray"
          command: ./gradlew -p dsl uploadArchives

  publish_easy-publish:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - run:
          name: "Publish EasyPublish to Gradle Central"
          command: ./gradlew -p publish publishPlugins

workflows:
  analyze_test_publish:
    jobs:
      - analyze:
          filters:
            tags:
              only: *

      - test:
          filters:
            tags:
              only: *

      - publish_dsl:
          requires:
            - analyze
            - test
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^dsl-[0-9](\.[0-9]+){1,2}(\-\w+\-[0-9]{1,2}){0,1}$/

      - publish_easy-publish:
          requires:
            - analyze
            - test
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^publish-[0-9](\.[0-9]+){1,2}$/
